### PR TITLE
Support for uint64

### LINKED ISSUE #44: [Feature Request] Support uint64 columns
Currently, if a copy of an influx database with `uint64` typed columns is attempted, these columns are skipped and the log shows 
``WARN[2020-10-10 16:32:49] Unhandled type &{data unsigned} in field data measuerment can``.

I will see if I can fix this in a PR.

### PR DESCRIPTION
**Pull request by ptoews**
Closes #44

### CODE REVIEW

**Comment by toni-moreno** [comment]
@ptoews Thank you for this PR. I can't validate the "unsigned" case no db's with unsigned support. So I trust you tested before.

I would like also you can add a new entry in the changelog file. Could you add it please?

**Comment by ptoews** [comment]
Yes, I did test it. Unsigned support in influx is currently only available with a special build flag, but it is supposed to be included by default as soon as the rest of the TICK stack supports it. Entry is now added to the changelog file

**Comment by toni-moreno** [comment]
Sorry again @ptoews  could you please set new version as "unreleased" yet ?  This is ` 0.6.8 ( unreleased )` , I will put the release date when some more new features/fixes added.

**Comment by ptoews** [comment]
Sure!

**Comment by toni-moreno** [comment]
Thank you very much for your contribution. !!

**Pull request merged**
